<a href="https://colab.research.google.com/github/hyeonahhh/TIL/blob/gh-pages/LECTURE_2_%EA%B0%95%EC%9D%98_%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NUMPY 기초
- array 단위로 데이터 관리

#### array 정의와 사용 방법
- 데이터 타입을 설정할 때에는 dtype 키워드 사용


In [2]:
import numpy as np
data1 = [1, 2, 3, 4, 5]
data2 = [6, 5, 4, 3, 2, 1]
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [3]:
ar2 = np.array(data1, dtype='float32')
ar2

array([1., 2., 3., 4., 5.], dtype=float32)

####다차원 배열 구성


In [4]:
ar3 = np.array([range(i, i + 3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

- full 함수

In [5]:
ar4 = np.full((3, 5), 3.14)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

- arange 함수

In [6]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- linspace 함수

In [7]:
ar6 = np.linspace(0, 1, 3)
ar6

array([0. , 0.5, 1. ])

- random 함수

In [9]:
ar7 = np.random.random((3, 3))
ar7

array([[0.87132749, 0.25031281, 0.01791934],
       [0.02987266, 0.81580102, 0.4335119 ],
       [0.23835907, 0.22838784, 0.10689042]])

In [10]:
ar8 = np.random.randint(0, 100, (3, 3)) #마지막은 배열 크기
ar8

array([[89, 21, 40],
       [78, 33, 80],
       [43, 74, 32]])

- eye 함수

In [11]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열 분할, 재구성, 결합
- ndim, shape, size

In [14]:
import numpy as np
x = np.random.randint(10, size=(3, 4, 5))
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)

x ndim: 3
x shape: (3, 4, 5)
x size: 60


- 배열 인덱싱

In [15]:
y = np.array([2, 4, 6, 8, 10])
print(y[0], y[-2])

2 8


- 다차원 배열 인덱싱

In [16]:
z = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15]])
print(z[1, 0])

3


In [17]:
z[0, 0] = 12
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

- 배열 슬라이싱

In [18]:
x = np.arange(10)
x[4:8]

array([4, 5, 6, 7])

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
x[5:]

array([5, 6, 7, 8, 9])

- 다차원 배열 슬라이싱

In [21]:
z = np.array([[2, 4, 6, 8], [3, 6, 9, 12], [4, 8, 12, 16]])
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

In [22]:
z[:3, ::2]

array([[ 2,  6],
       [ 3,  9],
       [ 4, 12]])

- 배열 재구조화(reshape 함수)

In [23]:
z = np.arange(1, 10).reshape(3, 3)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- 배열 결합

In [24]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y])
z

array([1, 2, 3, 3, 2, 1])

In [26]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], [7, 8, 9]])
v = np.vstack([x, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
y = np.array([[99], [99]])
z = np.hstack([grid, y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

- 배열 분할

In [28]:
x = [1, 2, 3, 77, 77, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


In [30]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [31]:
grid = np.arange(16).reshape((4, 4))
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


###NUMPY 심화

1. 유니버셜 함수
- 단항 유니버설 함수
  - 절대값 함수

In [32]:
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [33]:
np.abs(x)

array([2, 1, 0, 1, 2])

- 삼각함수, 역삼각함수, 지수함수, 로그함수 사용 가능

- out 인자

In [35]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [36]:
#배열 슬라이싱 사용
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out = y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


2. 집계 함수
- reduce 함수

In [37]:
x = np.arange(1, 5)
np.add.reduce(x)

10

- sum, max, min

In [38]:
s = np.random.random(1000)
np.min(s), np.max(s)

(0.00037120531918666266, 0.9998499823961404)

- axis

In [39]:
m = np.random.random((3, 4))
print(m)
m.max(axis = 0) #1로도 바꾸어보자

[[0.26571011 0.87019863 0.21235583 0.29105721]
 [0.44270852 0.47474344 0.66386792 0.60157702]
 [0.32215103 0.03412969 0.27628367 0.44467955]]


array([0.44270852, 0.87019863, 0.66386792, 0.60157702])

3. 브로드캐스팅 연산
- 크기가 같은 경우

In [40]:
x = np.array([0, 1, 2])
y = np.array([3, 3, 3])
x + y

array([3, 4, 5])

- 크기가 다른 경우

In [41]:
x = np.array([0, 1, 2])
x + 10

array([10, 11, 12])

#####브로드캐스팅의 기능(배열 확장의 3가지)
- 두 배열의 차원의 수가 서로 다를 경우, 더 작은 차원을 가진 배열의 앞(왼쪽 부분)을 1로 채운다.
- 두 배열의 형상이 어떤 차원에서도 일치하지 않는 경우, 해당 차원을 형상이 1인 배열이 늘어난다.
- 임의의 차원에서 크기가 일치하지 않고 1도 아닌 경우, 오류가 발생한다.

In [43]:
#1차원 배열 + 2차원 배열
x = np.array([0, 1, 2])
M = np.ones((3, 3))
x + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:
#두 배열 브로드캐스팅
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [47]:
x = np.linspace(0, 5, 50)
x = np.linspace(0, 5, 50)[:, np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)
#import matplotlib.pyplot as plt
#plt.imshow(z, origin='lower', extent=[0, 5, 0, 5], cmap='viridis')
#plt.colorbar();

4. 비교 연산자
- 행렬 데이터의 조건에 따른 결과 산출

In [48]:
#any 함수
import numpy as np
x = np.arange(10)
np.any(x < 5), np.any(x < 0)

(True, False)

In [49]:
#all 함수
x = np.arange(10)
np.all(x > 5), np.all(x < 10)

(False, True)

In [50]:
#1차원 배열 적용 사례
a = np.random.randint(1, 5, 5)
b = np.random.randint(1, 5, 5)
print(a, b)
a == b

[1 3 1 4 1] [4 3 3 4 1]


array([False,  True, False,  True,  True])

####펜시 인덱싱
- 인덱스 배열을 전달하고, 인덱스 배열의 값을 인덱스로 사용
- 복잡한 배열의 하위 집합에 매우 빠르게 접근


In [51]:
#1차원 적용 사례
a = np.arange(10)
b = np.array([3, 6, 9])
a[b]

array([3, 6, 9])

In [53]:
#다차원 배열 적용 사례
x = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

7. 정렬
- np.sort 함수
  - 원래 배열 데이터는 그대로 유지한 채 정렬된 배열이 복사본으로 반환

In [54]:
x = np.array([4, 1, 5, 2, 3])
print(x, np.sort(x))

[4 1 5 2 3] [1 2 3 4 5]


In [55]:
#x.sort -> 원래 배열 자체를 정렬
x.sort()
print(x)

[1 2 3 4 5]


In [57]:
#np.argsort 함수 -> 정렬된 요소의 인덱스를 반환
x = np.array([4, 1, 5, 2, 3])
i = np.argsort(x)
print(i)

[1 3 4 0 2]


In [58]:
#x_reverse -> 내림차순 정렬
x = np.array([4, 1, 5, 2, 3])
x_reverse = np.sort(x)[::-1]
print(x_reverse)

[5 4 3 2 1]


- 다차원 배열 정렬

In [59]:
#axis 인자 -> axis = 0일때, 각 열을 기준으로 정렬
X = np.array([[2, 0, 6], [7, 3, 4], [1, 5, 3]])
np.sort(X, axis = 0)

array([[1, 0, 3],
       [2, 3, 4],
       [7, 5, 6]])